'use client';

import { SnapshotMetric } from '@/lib/services/api-dagscan-request';
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Legend,
} from 'recharts';

interface ChartMetagraphSnapshotFeesProps {
  snapshotMetrics: SnapshotMetric[];
  metagraphAddress: string;
}

export function ChartMetagraphSnapshotFees({ snapshotMetrics, metagraphAddress }: ChartMetagraphSnapshotFeesProps) {
  const filteredMetrics = snapshotMetrics
    .filter(m => m.metagraphAddress === metagraphAddress)
    .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime())
    .map(m => ({
      date: new Date(m.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
      'Fees (DAG)': parseFloat(m.fees.toFixed(2)),
      fullDate: m.date,
    }));

  const totalFees = filteredMetrics.reduce((sum, m) => sum + m['Fees (DAG)'], 0);

  return (
    <div className="p-6 bg-gray-50 border-2 border-[#BA867B]" style={{ borderRight: '6px solid #8b675a', borderBottom: '6px solid #8b675a' }}>
      <h4 className="text-2xl font-bold text-black mb-4 uppercase">Snapshot Fees</h4>
      <div className="h-64 mb-4">
        <ResponsiveContainer width="100%" height="100%">
          <BarChart
            data={filteredMetrics}
            margin={{
              top: 5,
              right: 10,
              left: 0,
              bottom: 5,
            }}
          >
            <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
            <XAxis
              dataKey="date"
              tick={{ fontSize: 10, fill: '#000000', fontWeight: 'bold' }}
              angle={-45}
              textAnchor="end"
              height={60}
            />
            <YAxis
              tick={{ fontSize: 10, fill: '#000000', fontWeight: 'bold' }}
              label={{ value: 'DAG', angle: -90, position: 'insideLeft', style: { textAnchor: 'middle', fill: '#000000', fontWeight: 'bold' } }}
            />
            <Tooltip
              contentStyle={{
                backgroundColor: '#f9fafb',
                border: '2px solid #BA867B',
                borderRadius: '4px',
                color: '#111827',
              }}
              formatter={(value: number) => [`${value.toFixed(2)} DAG`, 'Fees']}
            />
            <Bar
              dataKey="Fees (DAG)"
              fill="#BA867B"
              radius={[4, 4, 0, 0]}
              stroke="#8b675a"
              strokeWidth={1}
            />
          </BarChart>
        </ResponsiveContainer>
      </div>
      <p className="text-sm text-black italic mb-2 font-bold">
        Fees generated by event-triggered global L0 snapshots: {totalFees.toFixed(2)} $DAG
      </p>
    </div>
  );
}
